// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Chat
{
    public int Id { get; set; }

    public int PublicacionIdPublicacion { get; set; }

    public int PerfilIdPerfil { get; set; }

    public virtual ICollection<Mensaje> Mensaje { get; set; } = new List<Mensaje>();

    public virtual ICollection<Notificacion> Notificacion { get; set; } = new List<Notificacion>();

    public virtual Perfil PerfilIdPerfilNavigation { get; set; }

    public virtual Publicacion PublicacionIdPublicacionNavigation { get; set; }
}