// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Models.Models;

public partial class comunidadsolidariaContext : DbContext
{
    public comunidadsolidariaContext(DbContextOptions<comunidadsolidariaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Chat> Chat { get; set; }

    public virtual DbSet<Donacion> Donacion { get; set; }

    public virtual DbSet<DonacionDetalleEstado> DonacionDetalleEstado { get; set; }

    public virtual DbSet<DonacionEstado> DonacionEstado { get; set; }

    public virtual DbSet<DonacionTipo> DonacionTipo { get; set; }

    public virtual DbSet<Envio> Envio { get; set; }

    public virtual DbSet<Localidad> Localidad { get; set; }

    public virtual DbSet<Mensaje> Mensaje { get; set; }

    public virtual DbSet<Notificacion> Notificacion { get; set; }

    public virtual DbSet<Novedad> Novedad { get; set; }

    public virtual DbSet<Perfil> Perfil { get; set; }

    public virtual DbSet<Provincia> Provincia { get; set; }

    public virtual DbSet<Publicacion> Publicacion { get; set; }

    public virtual DbSet<PublicacionTipo> PublicacionTipo { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<UsuarioReporte> UsuarioReporte { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Chat>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Chat_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 9999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.PerfilIdPerfil).HasColumnName("Perfil_idPerfil");
            entity.Property(e => e.PublicacionIdPublicacion).HasColumnName("Publicacion_idPublicacion");
            entity.Property(e => e.ReceptorIdReceptor).HasColumnName("Receptor_idReceptor");

            entity.HasOne(d => d.PerfilIdPerfilNavigation).WithMany(p => p.ChatPerfilIdPerfilNavigation)
                .HasForeignKey(d => d.PerfilIdPerfil)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Perfil_idPerfil");

            entity.HasOne(d => d.PublicacionIdPublicacionNavigation).WithMany(p => p.Chat)
                .HasForeignKey(d => d.PublicacionIdPublicacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Publicacion_idPublicacion");

            entity.HasOne(d => d.ReceptorIdReceptorNavigation).WithMany(p => p.ChatReceptorIdReceptorNavigation)
                .HasForeignKey(d => d.ReceptorIdReceptor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Receptor_idReceptor");
        });

        modelBuilder.Entity<Donacion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Donacion_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasColumnName("descripcion");
            entity.Property(e => e.DonacionTipoIdDonacionTipo).HasColumnName("DonacionTipo_idDonacionTipo");
            entity.Property(e => e.FechaHora).HasColumnName("fechaHora");
            entity.Property(e => e.PerfilDonanteIdPerfilDonante).HasColumnName("PerfilDonante_idPerfilDonante");
            entity.Property(e => e.PerfilIdPerfil).HasColumnName("Perfil_idPerfil");
            entity.Property(e => e.PublicacionIdPublicacion).HasColumnName("Publicacion_idPublicacion");

            entity.HasOne(d => d.DonacionTipoIdDonacionTipoNavigation).WithMany(p => p.Donacion)
                .HasForeignKey(d => d.DonacionTipoIdDonacionTipo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("DonacionTipo_idDonacionTipo");

            entity.HasOne(d => d.PerfilDonanteIdPerfilDonanteNavigation).WithMany(p => p.DonacionPerfilDonanteIdPerfilDonanteNavigation)
                .HasForeignKey(d => d.PerfilDonanteIdPerfilDonante)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("PerfilDonante_idPerfilDonante");

            entity.HasOne(d => d.PerfilIdPerfilNavigation).WithMany(p => p.DonacionPerfilIdPerfilNavigation)
                .HasForeignKey(d => d.PerfilIdPerfil)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Perfil_idPerfil");

            entity.HasOne(d => d.PublicacionIdPublicacionNavigation).WithMany(p => p.Donacion)
                .HasForeignKey(d => d.PublicacionIdPublicacion)
                .HasConstraintName("Publicacion_idPublicacion");
        });

        modelBuilder.Entity<DonacionDetalleEstado>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("DetalleDonacion_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 99999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasColumnName("descripcion");
            entity.Property(e => e.DonacionIdDonacion).HasColumnName("Donacion_idDonacion");

            entity.HasOne(d => d.DonacionIdDonacionNavigation).WithMany(p => p.DonacionDetalleEstado)
                .HasForeignKey(d => d.DonacionIdDonacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Donacion_idDonacion");
        });

        modelBuilder.Entity<DonacionEstado>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("DetalleDonacionTipo_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.DonacionIdDonacion).HasColumnName("Donacion_idDonacion");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasColumnName("nombre");

            entity.HasOne(d => d.DonacionIdDonacionNavigation).WithMany(p => p.DonacionEstado)
                .HasForeignKey(d => d.DonacionIdDonacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Donacion_idDonacion");
        });

        modelBuilder.Entity<DonacionTipo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("TipoDonacion_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasColumnName("descripcion");
        });

        modelBuilder.Entity<Envio>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Envio_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Aclaracion)
                .IsRequired()
                .HasColumnName("aclaracion");
            entity.Property(e => e.DireccionEmisor)
                .IsRequired()
                .HasColumnName("direccionEmisor");
            entity.Property(e => e.DireccionEreceptor)
                .IsRequired()
                .HasColumnName("direccionEReceptor");
            entity.Property(e => e.DonacionIddonacion).HasColumnName("donacion_iddonacion");
            entity.Property(e => e.LocalidadEmisorIdLocalidadEmisor).HasColumnName("LocalidadEmisor_idLocalidadEmisor");
            entity.Property(e => e.LocalidadReceptorIdLocalidadReceptor).HasColumnName("LocalidadReceptor_idLocalidadReceptor");
            entity.Property(e => e.PerfilEmisorIdPerfilEmisor).HasColumnName("PerfilEmisor_idPerfilEmisor");
            entity.Property(e => e.PerfilReceptorIdPerfilReceptor).HasColumnName("PerfilReceptor_idPerfilReceptor");

            entity.HasOne(d => d.DonacionIddonacionNavigation).WithMany(p => p.Envio)
                .HasForeignKey(d => d.DonacionIddonacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Donacion_idDonacion");

            entity.HasOne(d => d.LocalidadEmisorIdLocalidadEmisorNavigation).WithMany(p => p.EnvioLocalidadEmisorIdLocalidadEmisorNavigation)
                .HasForeignKey(d => d.LocalidadEmisorIdLocalidadEmisor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("LocalidadEmisor_idLocalidaEmir");

            entity.HasOne(d => d.LocalidadReceptorIdLocalidadReceptorNavigation).WithMany(p => p.EnvioLocalidadReceptorIdLocalidadReceptorNavigation)
                .HasForeignKey(d => d.LocalidadReceptorIdLocalidadReceptor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("LocalidadReceptor_idLocalidadreceptor");

            entity.HasOne(d => d.PerfilEmisorIdPerfilEmisorNavigation).WithMany(p => p.EnvioPerfilEmisorIdPerfilEmisorNavigation)
                .HasForeignKey(d => d.PerfilEmisorIdPerfilEmisor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("PerfilEmisor_idPerfilEmisor");

            entity.HasOne(d => d.PerfilReceptorIdPerfilReceptorNavigation).WithMany(p => p.EnvioPerfilReceptorIdPerfilReceptorNavigation)
                .HasForeignKey(d => d.PerfilReceptorIdPerfilReceptor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("PerfilReceptor_idPerfilReceptor");
        });

        modelBuilder.Entity<Localidad>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Localidad_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.CodigoPostal)
                .IsRequired()
                .HasColumnName("codigoPostal");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasColumnName("nombre");
            entity.Property(e => e.ProvinciaIdProvincia).HasColumnName("Provincia_idProvincia");

            entity.HasOne(d => d.ProvinciaIdProvinciaNavigation).WithMany(p => p.Localidad)
                .HasForeignKey(d => d.ProvinciaIdProvincia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Provincia_idProvincia");
        });

        modelBuilder.Entity<Mensaje>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Mensaje_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.ChatIdChat).HasColumnName("Chat_idChat");
            entity.Property(e => e.Contenido)
                .IsRequired()
                .HasColumnName("contenido");
            entity.Property(e => e.FechaHora)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fechaHora");
            entity.Property(e => e.PerfilIdPerfil).HasColumnName("Perfil_idPerfil");

            entity.HasOne(d => d.ChatIdChatNavigation).WithMany(p => p.Mensaje)
                .HasForeignKey(d => d.ChatIdChat)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Chat_idChat");

            entity.HasOne(d => d.PerfilIdPerfilNavigation).WithMany(p => p.Mensaje)
                .HasForeignKey(d => d.PerfilIdPerfil)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Perfil_idPerfil");
        });

        modelBuilder.Entity<Notificacion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Notificacion_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 199999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.ChatIdChat).HasColumnName("Chat_idChat");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasColumnName("descripcion");
            entity.Property(e => e.PerfilIdPerfil).HasColumnName("Perfil_idPerfil");
            entity.Property(e => e.PerfilReceptorIdPerfilReceptor).HasColumnName("PerfilReceptor_idPerfilReceptor");
            entity.Property(e => e.PublicacionIdPublicacion).HasColumnName("Publicacion_idPublicacion");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasColumnName("titulo");

            entity.HasOne(d => d.ChatIdChatNavigation).WithMany(p => p.Notificacion)
                .HasForeignKey(d => d.ChatIdChat)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Chat_idChat");

            entity.HasOne(d => d.PerfilIdPerfilNavigation).WithMany(p => p.NotificacionPerfilIdPerfilNavigation)
                .HasForeignKey(d => d.PerfilIdPerfil)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Perfil_idPerfil");

            entity.HasOne(d => d.PerfilReceptorIdPerfilReceptorNavigation).WithMany(p => p.NotificacionPerfilReceptorIdPerfilReceptorNavigation)
                .HasForeignKey(d => d.PerfilReceptorIdPerfilReceptor)
                .HasConstraintName("PerfilReceptor_idPerfilReceptor");

            entity.HasOne(d => d.PublicacionIdPublicacionNavigation).WithMany(p => p.Notificacion)
                .HasForeignKey(d => d.PublicacionIdPublicacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Publicacion_idPublicacion");
        });

        modelBuilder.Entity<Novedad>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Novedad_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasColumnName("descripcion");
            entity.Property(e => e.Fecha).HasColumnName("fecha");
            entity.Property(e => e.Imagen)
                .IsRequired()
                .HasColumnName("imagen");
            entity.Property(e => e.PerfilIdPerfil).HasColumnName("Perfil_idPerfil");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasColumnName("titulo");

            entity.HasOne(d => d.PerfilIdPerfilNavigation).WithMany(p => p.Novedad)
                .HasForeignKey(d => d.PerfilIdPerfil)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Perfil_idPerfil");
        });

        modelBuilder.Entity<Perfil>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Perfil_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Alias).HasColumnName("alias");
            entity.Property(e => e.Cbu).HasColumnName("cbu");
            entity.Property(e => e.CuitCuil).HasColumnName("cuitCuil");
            entity.Property(e => e.Descripcion).HasColumnName("descripcion");
            entity.Property(e => e.Imagen)
                .IsRequired()
                .HasColumnName("imagen");
            entity.Property(e => e.LocalidadIdLocalidad).HasColumnName("Localidad_idLocalidad");
            entity.Property(e => e.RazonSocial)
                .IsRequired()
                .HasColumnName("razonSocial");
            entity.Property(e => e.UsuarioIdUsuario).HasColumnName("Usuario_idUsuario");

            entity.HasOne(d => d.LocalidadIdLocalidadNavigation).WithMany(p => p.Perfil)
                .HasForeignKey(d => d.LocalidadIdLocalidad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Localidad_idLocalidad");

            entity.HasOne(d => d.UsuarioIdUsuarioNavigation).WithMany(p => p.Perfil)
                .HasForeignKey(d => d.UsuarioIdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Usuario_idUsuario");
        });

        modelBuilder.Entity<Provincia>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Provincia_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Publicacion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Publicacion_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 99999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasColumnName("descripcion");
            entity.Property(e => e.FechaCreacion).HasColumnName("fechaCreacion");
            entity.Property(e => e.Imagen).HasColumnName("imagen");
            entity.Property(e => e.LocalidadIdLocalidad).HasColumnName("Localidad_idLocalidad");
            entity.Property(e => e.PerfilIdPerfil).HasColumnName("Perfil_idPerfil");
            entity.Property(e => e.PublicacionTipoIdPublicacionTipo).HasColumnName("PublicacionTipo_idPublicacionTipo");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasColumnName("titulo");

            entity.HasOne(d => d.LocalidadIdLocalidadNavigation).WithMany(p => p.Publicacion)
                .HasForeignKey(d => d.LocalidadIdLocalidad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Localidad_idLocalidad_fkey");

            entity.HasOne(d => d.PerfilIdPerfilNavigation).WithMany(p => p.Publicacion)
                .HasForeignKey(d => d.PerfilIdPerfil)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Perfil_idPerfil");

            entity.HasOne(d => d.PublicacionTipoIdPublicacionTipoNavigation).WithMany(p => p.Publicacion)
                .HasForeignKey(d => d.PublicacionTipoIdPublicacionTipo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("PublicacionTipo_idPublicacionTipo");
        });

        modelBuilder.Entity<PublicacionTipo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PublicacionTipo_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 9999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Usuario_pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 9999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasColumnName("email");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasColumnName("password");
            entity.Property(e => e.Rol)
                .IsRequired()
                .HasColumnName("rol");
        });

        modelBuilder.Entity<UsuarioReporte>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Reporte _pkey");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasIdentityOptions(null, null, null, 999999L, null, null)
                .HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasColumnName("descripcion");
            entity.Property(e => e.FechaHora).HasColumnName("fechaHora");
            entity.Property(e => e.Motivo)
                .IsRequired()
                .HasColumnName("motivo");
            entity.Property(e => e.PerfilIdPerfil).HasColumnName("Perfil_idPerfil");
            entity.Property(e => e.PublicacionIdPublicacion).HasColumnName("Publicacion_idPublicacion");

            entity.HasOne(d => d.PerfilIdPerfilNavigation).WithMany(p => p.UsuarioReporte)
                .HasForeignKey(d => d.PerfilIdPerfil)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Perfil_idPerfil");

            entity.HasOne(d => d.PublicacionIdPublicacionNavigation).WithMany(p => p.UsuarioReporte)
                .HasForeignKey(d => d.PublicacionIdPublicacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Publicacion_idPublicacion");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}