// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class DetalleDonacion
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public int EnvioIdEnvio { get; set; }

    public int DonacionIdDonacion { get; set; }

    public virtual Donacion DonacionIdDonacionNavigation { get; set; }

    public virtual Envio EnvioIdEnvioNavigation { get; set; }
}