// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class DonacionDetalleEstado
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public int DonacionIdDonacion { get; set; }

    public int Cantidad { get; set; }

    public virtual ICollection<DonacionEstado> DonacionEstado { get; set; } = new List<DonacionEstado>();

    public virtual Donacion DonacionIdDonacionNavigation { get; set; }
}