// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class DonacionEstado
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public int DonacionDetalleEstadoIdDonacionDetalleEstado { get; set; }

    public virtual DonacionDetalleEstado DonacionDetalleEstadoIdDonacionDetalleEstadoNavigation { get; set; }
}