// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Donacion
{
    public int Id { get; set; }

    public DateTime? FechaHora { get; set; }

    public int PerfilIdPerfil { get; set; }

    public int DonacionTipoIdDonacionTipo { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<DetalleDonacion> DetalleDonacion { get; set; } = new List<DetalleDonacion>();

    public virtual DonacionTipo DonacionTipoIdDonacionTipoNavigation { get; set; }

    public virtual Perfil PerfilIdPerfilNavigation { get; set; }

    public virtual ICollection<Publicacion> Publicacion { get; set; } = new List<Publicacion>();
}