// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Donacion
{
    public int Id { get; set; }

    public DateTime FechaHora { get; set; }

    public int PerfilIdPerfil { get; set; }

    public int DonacionTipoIdDonacionTipo { get; set; }

    public string Descripcion { get; set; }

    public int PerfilDonanteIdPerfilDonante { get; set; }

    public int? PublicacionIdPublicacion { get; set; }

    public virtual ICollection<DonacionDetalleEstado> DonacionDetalleEstado { get; set; } = new List<DonacionDetalleEstado>();

    public virtual ICollection<DonacionEstado> DonacionEstado { get; set; } = new List<DonacionEstado>();

    public virtual DonacionTipo DonacionTipoIdDonacionTipoNavigation { get; set; }

    public virtual ICollection<Envio> Envio { get; set; } = new List<Envio>();

    public virtual Perfil PerfilDonanteIdPerfilDonanteNavigation { get; set; }

    public virtual Perfil PerfilIdPerfilNavigation { get; set; }

    public virtual Publicacion PublicacionIdPublicacionNavigation { get; set; }
}