// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Donacion
{
    public int Id { get; set; }

    public DateOnly FechaHora { get; set; }

    public int UsuarioIdUsuario { get; set; }

    public int TipoDonacionIdTipoDonacion { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<DetalleDonacion> DetalleDonacion { get; set; } = new List<DetalleDonacion>();

    public virtual TipoDonacion TipoDonacionIdTipoDonacionNavigation { get; set; }

    public virtual Usuario UsuarioIdUsuarioNavigation { get; set; }
}