// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Envio
{
    public int Id { get; set; }

    public string DireccionEmisor { get; set; }

    public int PerfilEmisorIdPerfilEmisor { get; set; }

    public int PerfilReceptorIdPerfilReceptor { get; set; }

    public int LocalidadEmisorIdLocalidadEmisor { get; set; }

    public int LocalidadReceptorIdLocalidadReceptor { get; set; }

    public string DireccionEreceptor { get; set; }

    public int DonacionIddonacion { get; set; }

    public string Aclaracion { get; set; }

    public virtual Donacion DonacionIddonacionNavigation { get; set; }

    public virtual Localidad LocalidadEmisorIdLocalidadEmisorNavigation { get; set; }

    public virtual Localidad LocalidadReceptorIdLocalidadReceptorNavigation { get; set; }

    public virtual Perfil PerfilEmisorIdPerfilEmisorNavigation { get; set; }

    public virtual Perfil PerfilReceptorIdPerfilReceptorNavigation { get; set; }
}