// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Envio
{
    public int Id { get; set; }

    public string Direccion { get; set; }

    public int LocalidadIdLocalidad { get; set; }

    public DateTime FechaEnvio { get; set; }

    public int EstadoIdEstado { get; set; }

    public virtual ICollection<DetalleDonacion> DetalleDonacion { get; set; } = new List<DetalleDonacion>();

    public virtual EstadoTipo EstadoIdEstadoNavigation { get; set; }

    public virtual Localidad LocalidadIdLocalidadNavigation { get; set; }
}