// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class EstadoTipo
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Envio> Envio { get; set; } = new List<Envio>();
}