// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Localidad
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string CodigoPostal { get; set; }

    public int ProvinciaIdProvincia { get; set; }

    public virtual ICollection<Envio> EnvioLocalidadEmisorIdLocalidadEmisorNavigation { get; set; } = new List<Envio>();

    public virtual ICollection<Envio> EnvioLocalidadReceptorIdLocalidadReceptorNavigation { get; set; } = new List<Envio>();

    public virtual ICollection<Perfil> Perfil { get; set; } = new List<Perfil>();

    public virtual Provincia ProvinciaIdProvinciaNavigation { get; set; }

    public virtual ICollection<Publicacion> Publicacion { get; set; } = new List<Publicacion>();
}