// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Mensaje
{
    public int Id { get; set; }

    public string Contenido { get; set; }

    public DateTime FechaHora { get; set; }

    public int ChatIdChat { get; set; }

    public int PerfilIdPerfil { get; set; }

    public virtual Chat ChatIdChatNavigation { get; set; }

    public virtual Perfil PerfilIdPerfilNavigation { get; set; }
}