// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Notificacion
{
    public int Id { get; set; }

    public int UsuarioIdUsuario { get; set; }

    public int ChatIdChat { get; set; }

    public virtual Chat ChatIdChatNavigation { get; set; }

    public virtual Usuario UsuarioIdUsuarioNavigation { get; set; }
}