// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Notificacion
{
    public int Id { get; set; }

    public int PerfilIdPerfil { get; set; }

    public int ChatIdChat { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public int PublicacionIdPublicacion { get; set; }

    public int? PerfilReceptorIdPerfilReceptor { get; set; }

    public virtual Chat ChatIdChatNavigation { get; set; }

    public virtual Perfil PerfilIdPerfilNavigation { get; set; }

    public virtual Perfil PerfilReceptorIdPerfilReceptorNavigation { get; set; }

    public virtual Publicacion PublicacionIdPublicacionNavigation { get; set; }
}