// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Novedad
{
    public int Id { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public DateOnly Fecha { get; set; }

    public int PerfilIdPerfil { get; set; }

    public byte[] Imagen { get; set; }

    public virtual Perfil PerfilIdPerfilNavigation { get; set; }
}