// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Perfil
{
    public int Id { get; set; }

    public int CuitCuil { get; set; }

    public string RazonSocial { get; set; }

    public string Descripcion { get; set; }

    public int Cbu { get; set; }

    public string Alias { get; set; }

    public int UsuarioIdUsuario { get; set; }

    public int LocalidadIdLocalidad { get; set; }

    public byte[] Imagen { get; set; }

    public virtual ICollection<Chat> Chat { get; set; } = new List<Chat>();

    public virtual ICollection<Donacion> Donacion { get; set; } = new List<Donacion>();

    public virtual Localidad LocalidadIdLocalidadNavigation { get; set; }

    public virtual ICollection<Mensaje> Mensaje { get; set; } = new List<Mensaje>();

    public virtual ICollection<Notificacion> Notificacion { get; set; } = new List<Notificacion>();

    public virtual ICollection<Novedad> Novedad { get; set; } = new List<Novedad>();

    public virtual ICollection<Publicacion> Publicacion { get; set; } = new List<Publicacion>();

    public virtual Usuario UsuarioIdUsuarioNavigation { get; set; }
}