// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Perfil
{
    public int Id { get; set; }

    public long CuitCuil { get; set; }

    public string RazonSocial { get; set; }

    public string Descripcion { get; set; }

    public long Cbu { get; set; }

    public string Alias { get; set; }

    public int UsuarioIdUsuario { get; set; }

    public int LocalidadIdLocalidad { get; set; }

    public byte[] Imagen { get; set; }

    public virtual ICollection<Chat> ChatPerfilIdPerfilNavigation { get; set; } = new List<Chat>();

    public virtual ICollection<Chat> ChatReceptorIdReceptorNavigation { get; set; } = new List<Chat>();

    public virtual ICollection<Donacion> DonacionPerfilDonanteIdPerfilDonanteNavigation { get; set; } = new List<Donacion>();

    public virtual ICollection<Donacion> DonacionPerfilIdPerfilNavigation { get; set; } = new List<Donacion>();

    public virtual ICollection<Envio> EnvioPerfilEmisorIdPerfilEmisorNavigation { get; set; } = new List<Envio>();

    public virtual ICollection<Envio> EnvioPerfilReceptorIdPerfilReceptorNavigation { get; set; } = new List<Envio>();

    public virtual Localidad LocalidadIdLocalidadNavigation { get; set; }

    public virtual ICollection<Mensaje> Mensaje { get; set; } = new List<Mensaje>();

    public virtual ICollection<Notificacion> NotificacionPerfilIdPerfilNavigation { get; set; } = new List<Notificacion>();

    public virtual ICollection<Notificacion> NotificacionPerfilReceptorIdPerfilReceptorNavigation { get; set; } = new List<Notificacion>();

    public virtual ICollection<Novedad> Novedad { get; set; } = new List<Novedad>();

    public virtual ICollection<Publicacion> Publicacion { get; set; } = new List<Publicacion>();

    public virtual Usuario UsuarioIdUsuarioNavigation { get; set; }

    public virtual ICollection<UsuarioReporte> UsuarioReporte { get; set; } = new List<UsuarioReporte>();
}