// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Publicacion
{
    public int Id { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public byte[] Imagen { get; set; }

    public DateOnly FechaCreacion { get; set; }

    public int LocalidadIdLocalidad { get; set; }

    public int UsuarioIdUsuario { get; set; }

    public virtual ICollection<Chat> Chat { get; set; } = new List<Chat>();

    public virtual Localidad LocalidadIdLocalidadNavigation { get; set; }

    public virtual Usuario UsuarioIdUsuarioNavigation { get; set; }
}