// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class TipoDonacion
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Donacion> Donacion { get; set; } = new List<Donacion>();
}