// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Contraseña { get; set; }

    public virtual ICollection<Chat> Chat { get; set; } = new List<Chat>();

    public virtual ICollection<Donacion> Donacion { get; set; } = new List<Donacion>();

    public virtual ICollection<Mensaje> Mensaje { get; set; } = new List<Mensaje>();

    public virtual ICollection<Notificacion> Notificacion { get; set; } = new List<Notificacion>();

    public virtual ICollection<Perfil> Perfil { get; set; } = new List<Perfil>();

    public virtual ICollection<Publicacion> Publicacion { get; set; } = new List<Publicacion>();
}