// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class UsuarioReporte
{
    public int Id { get; set; }

    public string Motivo { get; set; }

    public string Descripcion { get; set; }

    public int PublicacionIdPublicacion { get; set; }

    public int PerfilIdPerfil { get; set; }

    public DateOnly FechaHora { get; set; }

    public virtual Perfil PerfilIdPerfilNavigation { get; set; }

    public virtual Publicacion PublicacionIdPublicacionNavigation { get; set; }
}